# Generated by Django 4.1.2 on 2022-12-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dOB',
            field=models.DateField(blank=True, default='1999-01-22', null=True),
        ),
    ]
